# Generated by Django 4.2.4 on 2023-08-11 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_post_dizayne'),
    ]

    operations = [
        migrations.CreateModel(
            name='My_Sills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('sila', models.IntegerField(max_length=200)),
            ],
        ),
    ]
