# Generated by Django 4.2.4 on 2023-08-13 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_my_sills'),
    ]

    operations = [
        migrations.CreateModel(
            name='My_silka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('silkasi', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='my_sills',
            name='sila',
            field=models.IntegerField(),
        ),
    ]
