# Generated by Django 4.2.4 on 2023-08-12 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_about_me_alter_my_sills_sila'),
    ]

    operations = [
        migrations.CreateModel(
            name='Link_me',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('link', models.URLField()),
            ],
        ),
    ]
