# Generated by Django 4.2.4 on 2023-08-13 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_my_silka_alter_my_sills_sila'),
    ]

    operations = [
        migrations.CreateModel(
            name='My_About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('info', models.TextField()),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
    ]
